# Generated by Django 4.2.7 on 2023-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100, unique=True)),
                ('empname', models.CharField(max_length=150, null=True)),
                ('dateb', models.DateField(null=True)),
                ('datej', models.DateField(null=True)),
                ('department', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(max_length=2, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('salary', models.IntegerField(max_length=10, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
