# Generated by Django 5.0 on 2023-12-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_login_manager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="login",
        ),
    ]
