# Generated by Django 5.0 on 2023-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_delete_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emp",
            name="position",
        ),
        migrations.AddField(
            model_name="emp",
            name="gender",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="emp",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emp",
            name="salary",
            field=models.IntegerField(null=True),
        ),
    ]
