# Generated by Django 5.0 on 2023-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_emp_position_emp_gender_alter_emp_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emp",
            name="phno",
            field=models.IntegerField(null=True),
        ),
    ]
