# Generated by Django 5.0 on 2023-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_emp_phno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emp",
            name="department",
            field=models.CharField(
                choices=[
                    ("Coding", "Coding"),
                    ("Debugging", "Debugging"),
                    ("Testing", "Testing"),
                    ("Animation", "Animation"),
                    ("Design", "Design"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emp",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=100,
                null=True,
            ),
        ),
    ]
